RebelInventory/Controllers/EquipmentController.cs
using InventoryData;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RebelInventory.Models.Equipment;
using System.Linq;

namespace RebelInventory.Controllers
{
    public class EquipmentController : Controller
    {
        private IMilitaryAsset _equipments;
        private IChangeValues _changeValues;
        private IStorageLocations _storageLocations;

        public EquipmentController(IMilitaryAsset assets, IChangeValues changeValues, IStorageLocations locations)
        {
            _equipments = assets;
            _changeValues = changeValues;
            _storageLocations = locations;

        }

        public IActionResult Index()
        {
            var equipmentModels = _equipments.GetAll();

            var listingResult = equipmentModels
                .Select(result => new EquipmentIndexListingModel
                {
                    Id = result.Id,
                    ImageUrl = result.ImageUrl,
                    Name = result.Name,
                    Type = _equipments.GetType(result.Id),
                    Amount = result.Amount
                });

            var model = new EquipmentIndexModel()
            {
                Equipments = listingResult
            };

            return View(model);
        }

        [Authorize]
        public IActionResult Detail(int id)
        {
            var equipment = _equipments.GetById(id);

            var model = new EquipmentDetailModel
            {
                EquipmentId = id,
                Name = equipment.Name,
                Description = equipment.Description,
                Amount = equipment.Amount,
                AmountUnderRepair = _equipments.GetAmountUnderRepair(id).AmountUnderRepair,
                AmountAvailable = equipment.Amount - _equipments.GetAmountUnderRepair(id).AmountUnderRepair,
                ImageUrl = equipment.ImageUrl,
                Type = _equipments.GetType(id),
                StorageLocation = _equipments.GetCurrentLocation(id).Name,
                LocationNames = _storageLocations.GetStorageLocationNames()
            };

            if (_equipments.GetType(id) == "Starship")
            {
                model.HasShields = _equipments.GetHasShields(id);
                model.NoOfLaserCannons = _equipments.GetNoOfLaserCannons(id);
                model.NoOfIonCannons = _equipments.GetNoOfIonCannons(id);
                model.NoOfProtonLaunchers = _equipments.GetNoOfProtonLaunchers(id);
                model.NoOfConcussionLaunchers = _equipments.GetNoOfConcussionLaunchers(id);
            }
            else if (_equipments.GetType(id) == "Vehicle")
            {
                model.VehicleHasShields = _equipments.GetVehicleHasShields(id);
                model.VehicleNoOfLasersCannons = _equipments.GetVehicleNoOfLasersCannons(id);
                model.MaxPassengers = _equipments.GetMaxPassengers(id);
            }
            else
            {
                model.IsOneHanded = _equipments.GetIsOneHanded(id);
                model.IsTwoHanded = _equipments.GetIsTwoHanded(id);
                model.IsTripodMounted = _equipments.GetIsTripodMounted(id);
            }


            return View(model);
        }

        [HttpPost]
        public IActionResult RelocateEquipment(int id, string relocateEquipmentDD)
        {
            // compare string to location names and get location id

            

            _changeValues.RelocateEquipment(id, relocateEquipmentDD);


            // change location id on equipment to new id


            return RedirectToAction("Detail", new { id = id });
        }
        
        [HttpPost]
        public IActionResult AddAmount(int id, int addAmountTB)
        {
            // get item and add amount to it, then save to db
            _changeValues.AddAmount(id, addAmountTB);

            return RedirectToAction("Detail", new { id = id });
        }

        [HttpPost]
        public IActionResult RemoveAmount(int id, int removeAmountTB)
        {
            // get item and remove amount from it, then save to db

            // need to alert user if number not accepted (number makes total go below 0)
            _changeValues.RemoveAmount(id, removeAmountTB);

            return RedirectToAction("Detail", new { id = id });
        }

        [HttpPost]
        public IActionResult SendToRepair(int id, int sendToRepairTB)
        {
            _changeValues.SendToRepair(id, sendToRepairTB);

            return RedirectToAction("Detail", new { id = id });
        }

        [HttpPost]
        public IActionResult ReturnFromRepair(int id, int returnFromRepairTB)
        {
            _changeValues.ReturnFromRepair(id, returnFromRepairTB);

            return RedirectToAction("Detail", new { id = id });
        }
    }
}

RebelInventory/Controllers/InventoryController.cs
using InventoryData;
using Microsoft.AspNetCore.Mvc;
using RebelInventory.Models.Inventory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RebelInventory.Controllers
{
    public class InventoryController : Controller
    {
        private IInventoryList _inventoryList;

        public InventoryController(IInventoryList inventoryList)
        {
            _inventoryList = inventoryList;
        }

        public IActionResult Index()
        {
            var allInventory = _inventoryList.GetAll();

            var inventoryListModels = allInventory.Select(result => new InventoryDetailModel
            {
                Id = result.Id,
                Name = result.Name,
                Type = _inventoryList.GetType(result.Id),
                Location = result.Location.Name,
                Amount = result.Amount,
                AmountUnderRepair = _inventoryList.GetAmountUnderRepair(result.Id).AmountUnderRepair,
                AmountAvailable = result.Amount - _inventoryList.GetAmountUnderRepair(result.Id).AmountUnderRepair
            }).ToList();

            var model = new InventoryIndexModel()
            {
                InventoryItems = inventoryListModels
            };

            return View(model);


        }
    }
}

RebelInventory/Controllers/LocationController.cs
using InventoryData;
using Microsoft.AspNetCore.Mvc;
using RebelInventory.Models.StorageLocations;
using System.Linq;

namespace RebelInventory.Controllers
{
    public class LocationController : Controller
    {
        private IStorageLocations _location;

        public LocationController(IStorageLocations location)
        {
            _location = location;
        }

        public IActionResult Index()
        {
            var locations = _location.GetAll().Select(location => new StorageLocationDetailModel
            {
                Id = location.Id,
                LocationName = location.Name,
                TotalAmountOfEquipment = _location.GetEquipmentTotalAtLocation(location.Id)
            });

            var model = new StorageLocationIndexModel()
            {
                Locations = locations
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {

            // get list of equipment at current location
            var equipmentModels = _location.GetAllEquipmentAtLocation(id);

            var listingResult = equipmentModels
                .Select(result => new StorageLocationDetailListingModel
                {
                    Id = result.Id,
                    Name = result.Name,
                    Type = _location.GetType(result.Id),
                    Amount = result.Amount,
                    AmountUnderRepair = _location.GetAmountUnderRepair(result.Id).AmountUnderRepair,
                    AmountAvailable = result.Amount - _location.GetAmountUnderRepair(result.Id).AmountUnderRepair
                });


            // get location details
            var location = _location.Get(id);

            var model = new StorageLocationDetailModel
            {
                Id = location.Id,
                LocationName = location.Name,
                LocationDescription = location.Description,
                ImageUrl = location.ImageUrl,
                TotalAmountOfEquipment = _location.GetEquipmentTotalAtLocation(location.Id),
                TotalAmountUnderRepair = _location.GetTotalAmountUnderRepair(location.Id),
                TotalAmountAvailable = _location.GetTotalAmountAvaiilable(location.Id),
                ListingDetails = listingResult
            };

            return View(model);
        }
    }
}

RebelInventory/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

@using Microsoft.AspNetCore.Identity
@using RebelInventory.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rebel Inventory</title>
    @Html.Raw(JavaScriptSnippet.FullScript)
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Coda" />
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="custom-header mdl-layout__header mdl-layout__header--waterfall" id="NavBar">
            <div class="mdl-layout__header-row" id="BlackText">
                <!-- Title -->
                <span class="mdl-layout-title logo"><a href="/">Rebel Inventory</a></span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="mdl-navigation__link" asp-controller="Inventory" asp-action="Index">Inventory List</a>
                    <a class="mdl-navigation__link" asp-controller="Location" asp-action="Index">Storage Locations</a>
                    <a class="mdl-navigation__link" asp-controller="Equipment" asp-action="Index">Equipment</a>

                    @if (SignInManager.IsSignedIn(User))
    {
                <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm">


                    <a asp-area="" asp-controller="Manage" asp-action="Index" title="Manage" id="username">Hello @UserManager.GetUserName(User)!</a>

                    <button type="submit" class="btn btn-link navbar-btn navbar-link" id="LogOut">Log out</button>

                </form>
}
else
{

                <a class="mdl-navigation__link" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                <a class="mdl-navigation__link" asp-area="" asp-controller="Account" asp-action="Login">Log in</a>

}
                </nav>
            </div>
        </header>
        <div class="page-content">
            @RenderBody()
        </div>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>